trainingInput:
  scaleTier: CUSTOM
  masterType: complex_model_m_gpu    
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    maxTrials: 20
    maxParallelTrials: 4
    enableTrialEarlyStopping: TRUE
    params:
    - parameterName: batchsize
      type: INTEGER
      minValue: 16
      maxValue: 512
      scaleType: UNIT_LOG_SCALE
    - parameterName: learn_rate
      type: DOUBLE
      minValue: 0.01
      maxValue: 0.2
      scaleType: UNIT_LINEAR_SCALE  
    - parameterName: embedding
      type: CATEGORICAL
      categoricalValues: ['0', '1']  
    - parameterName: hidden_units
      type: CATEGORICAL
      categoricalValues: ["64,16", "64,16,4", "120, 48, 24, 12"]  