trainingInput:
  scaleTier: CUSTOM
  masterType: complex_model_m_gpu    
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    maxTrials: 10
    maxParallelTrials: 3
    enableTrialEarlyStopping: TRUE
    params:
    - parameterName: feat_eng_cols
      type: CATEGORICAL
      categoricalValues: ["ON", "OFF"]       
    - parameterName: batchsize
      type: INTEGER
      minValue: 16
      maxValue: 512
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: dropout
      type: DOUBLE
      minValue: .2
      maxValue: .9
      scaleType: UNIT_LINEAR_SCALE      
    - parameterName: hidden_units
      type: CATEGORICAL
      categoricalValues: ["64,16", "64,16,4", "120, 48, 24, 12"]  
    - parameterName: learn_rate
      type: DOUBLE
      minValue: 0.01
      maxValue: 0.2
      scaleType: UNIT_LINEAR_SCALE        